version: '3.8'
    
services:

  nginx:
    #build: ./nginx
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  
  frontend:
    build: ./frontend
    image: frontend-service:latest
    ports:
    - target: 5000
      published: 5000
    depends_on:
      - backend
  
  backend:
    build: ./backend
    image: backend-service:latest
    ports:
    - target: 5001
      published: 5001
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database
  
  database:
    image: mysql:latest
    environment:
#       - MYSQL_PASSWORD: password
#       -  MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    ports:
    - target: 3306
      published: 3306
    volumes:
       - /database:/var/lib/mysql
