version: '3.8'

networks: 
    appnetwork:
    
services:

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    - target: 443
      published: 443
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    networks: 
       - appnetwork
  
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend-service:latest
    ports:
    - target: 5000
      published: 5000
    depends_on:
      - backend
    networks:
       - appnetwork
  
  backend:
    container_name: backend
    build: ./backend
    image: backend-service:latest
    ports:
    - target: 5001
      published: 5001
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database
    networks:
       - appnetwork
  
  database:
    container_name: database
    image: mysql:latest
    environment:
#       - MYSQL_PASSWORD: password
#       -  MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         - MYSQL_ALLOW_EMPTY_PASSWORD=1
 
    ports:
    - target: 3306
      published: 3306
    networks:
       - appnetwork
    volumes:
       - /database:/var/lib/mysql
