version: '3.8'
    
services:

  frontend:
    build: krystalsimmonds/sfia_2_frontend
    expose:
      - 5000
    depends_on:
      - backend
  
  backend:
    build: krystalsimmonds/sfia_2_backend
    expose:
      - 5001
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URI=${DATABASE_URI}
      - TEST_DATABASE_URI=${TEST_DATABASE_URI}
    depends_on:
      - database
  
  database:
    build: krystalsimmonds/sfia_2_database
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
     - 3306
    volumes:
     - /database:/var/lib/mysql
       
       
  nginx:
    image: nginx:latest
    ports:
     - 80:80
    volumes:
     - type: bind
       source: ./nginx/nginx.conf
       target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
