version: '3.8'
    
services:

  frontend:
    build: ./frontend
    expose:
      - 5000
    depends_on:
      - backend
  
  backend:
    build: ./backend
    expose:
      - 5001
    environment:
      - DB_PASSWORD="beautifuldb"
      - DATABASE_URI="mysql+pymysql://root:beautifuldb@mysql:3306/users"
    depends_on:
      - database
  
  database:
    build: ./database
    environment:
     - MYSQL_ROOT_PASSWORD=password
    expose:
     - 3306
    volumes:
     - /database:/var/lib/mysql
       
       
  nginx:
    #build: ./nginx
    image: nginx:latest
    ports:
     - 80:80
    volumes:
     - type: bind
       source: ./nginx/nginx.conf
       target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
