apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database-service
  ports: 
  - protocol: TCP
    port: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  labels: 
    app: database-service
spec:
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
      - name: database-service
        image: krystalsimmonds/sfia_2_database
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASSWORD
          value: ${DB_PASSWORD}
        - name: DATABASE_URI
          value: ${DATABASE_URI}
        - name: TEST_DATABASE_URI
          value: ${TEST_DATABASE_URI}
        - name: MYSQL_ROOT_PASSWORD
          value: ${MYSQL_ROOT_PASSWORD}
